### ISSUE TITLE
Installing Test Kitchen

### ISSUE THREAD

**Issue by jghaines** [test-kitchen/kitchen-docs#24]
Shouldn't we recommend install Chef DK instead of the gem based solution?
https://downloads.getchef.com/chef-dk/

**Comment by fnichol** [comment]
Hi there @jghaines! You're totally right, that would simplify that part of the guide. I'm hoping to get to this soon, but if you're up to it, we can work though a PR :smile:

**Comment by yohei1126** [comment]
It seems that test kitchen does not work with Chef-DK's ruby :(

**Comment by lloydde** [comment]
@yohei1126 what is the symptom? Could you share the command and output?

**Comment by yohei1126** [comment]
Sorry. That was my mistake. It works well.

**Comment by cheeseplus** [comment]
Taken care of by https://github.com/test-kitchen/kitchen-docs/pull/56
