### ISSUE TITLE
mention ChefDK

### ISSUE THREAD

**Issue by juliandunn** [test-kitchen/kitchen-docs#29]
The front page of kitchen.ci still advises you to install Test Kitchen via a `gem install` -- this is unnecessary since it's bundled with ChefDK, so we should mention that as the preferred option.

**Comment by lloydde** [comment]
test-kitchen/kitchen-docs/#24#issuecomment-74678615 suggests "It seems that test kitchen does not work with Chef-DK's ruby :("

**Comment by juliandunn** [comment]
That makes no sense since ChefDK is bundled with test kitchen.

**Comment by cheeseplus** [comment]
Gonna fix this eventually.

**Comment by cheeseplus** [comment]
This is taken care of by #56
