### ISSUE TITLE
"Usually not a big for most users" ?

### ISSUE THREAD

**Issue by lloydde** [test-kitchen/kitchen-docs#32]
@calebhailey what is meant there?
https://github.com/test-kitchen/kitchen-docs/blame/master/source/docs/getting-started/running-verify.md#L49

**Comment by calebhailey** [comment]
No idea. I'd have to defer to @fnichol on that one, sorry.

**Comment by cheeseplus** [comment]
Usually not a big deal is what it is supposed to read - I'll get a PR in as soon as time allows if someone else doesn't.

**Comment by xmik** [comment]
This was fixed in https://github.com/test-kitchen/kitchen-docs/pull/41
