### ISSUE TITLE
External links from "Installing Test Kitchen" page is broken

### ISSUE THREAD

**Issue by gluefactory** [test-kitchen/kitchen-docs#38]
The links from "and the folks over at the #learnchef website have a handy Workstation Setup that we can follow to get us started" are broken.

I forked the docs and added some links to the individual sites (Chef, Vagrant, Git and VirtualBox) because I couldn't find a combined page anymore. I'm happy to create a pull-request, or add the file here, but I read I should discuss on IRC first. Can't find anyone over there to discuss with. Maybe I need to wait longer.

Let me know the best thing to do. Ta

**Comment by cheeseplus** [comment]
Do you happen to have the links available? I'm typically in IRC all the time but I'm on the road in Europe with clients so I'm not as glued as otherwise would be. PRs are always welcome and especially when I'm under time constraints, very much appreciated.

**Comment by gluefactory** [comment]
What's the best thing to do with this? I haven't seen any feedback, except about which channels to use. Can I submit now - or does someone need to approve/merge/edit the changes?

**Comment by cheeseplus** [comment]
This is fixed in https://github.com/test-kitchen/kitchen-docs/pull/56
