### ISSUE TITLE
Creating-cookbook: 'kitchen create' - Stuck Waiting for SSH server on 127.0.0.1

### ISSUE THREAD

**Issue by lewisst** [test-kitchen/kitchen-docs#52]
Ran into a issue the the instructions following the creating-cookbook `kitchen create`  where upon booting the VM the SSH key couldn't be created. Command just paused at :

```
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
```

Running on:

- Chef: 12.16.42
- Vagrant Version: 1.8.7
- VirtualBox: 5.0.30
- Mac OS X: 10.11.6

Fix was found here http://stackoverflow.com/a/40142286/7216518 and involved a edit the `.kitchen.yaml` to enabled cableconnected1: on

``` yaml
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'
```

Also while not a issue with kitchen I will include here in case anyone finds it,  as I needed to fix to get this far:

Curl broken in macOS vagrant 1.8.7 https://github.com/mitchellh/vagrant/issues/7997
Workaround:
```
sudo rm -f /opt/vagrant/embedded/bin/curl
```

**Comment by kalebwalton** [comment]
Ran into this myself. Thanks for the cableconnected1 fix.

**Comment by cheeseplus** [comment]
It's worth noting that newer versions of Vagrant combined with newer base boxes from bento doesn't have this issue.
