### ISSUE TITLE
Expose kitchen.ci under HTTPS

### ISSUE THREAD

**Issue by Nowaker** [test-kitchen/kitchen-docs#79]
...and redirect http://kitchen.ci/ to https://kitchen.ci/. Security, integrity and privacy first! 😃

**Comment by cheeseplus** [comment]
Unfortunately I don't have the domain name to doing that is rather hard at the moment.

**Comment by Nowaker** [comment]
@cheeseplus kitchen.ci A records resolve to Amazon EC2 instances. So all that's needed is access to these EC2 instances to setup TLS/SSL. Access to the domain isn't required. I can assist with that if needed.

```
nowaker@nwkr-mbp ~ % host kitchen.ci
kitchen.ci has address 54.225.132.188
kitchen.ci has address 50.17.207.130
kitchen.ci has address 54.225.111.83
kitchen.ci has address 50.19.118.169
kitchen.ci has address 54.225.153.48
kitchen.ci has address 50.19.250.53
kitchen.ci has address 50.19.107.206
kitchen.ci has address 54.221.211.25

nowaker@nwkr-mbp ~ % host 50.19.118.169
169.118.19.50.in-addr.arpa domain name pointer ec2-50-19-118-169.compute-1.amazonaws.com.
```

**Comment by cheeseplus** [comment]
It's actually hosted via Heroku so those addresses aren't really meaningful. This has been a longstanding issue where we got the heroku account migrated to our control but still have no access to DNS/registrar.

**Comment by Nowaker** [comment]
According to [this article](https://devcenter.heroku.com/articles/ssl), it's now possible to submit an SSL cert to Heroku free of charge. `heroku certs:add server.crt server.key` The cert itself is easily obtainable with Let's Encrypt. No DNS/registrar is needed for this if HTTP verification method route is taken. Here's how:

```
brew install certbot
certbot --config-dir=~/.letsencrypt/config --work-dir=~/.letsencrypt/work --logs-dir=~/.letsencrypt/log certonly --manual --agree-tos -d kitchen.ci --email YOUR_EMAIL
```

You'll then receive instructions like this:
```
Create a file containing just this data:

[snipped-1]

And make it available on your web server at this URL:

http://virtkick.com/.well-known/acme-challenge/[snipped-2]

-------------------------------------------------------------------------------
Press Enter to Continue
```

Just push the verification file to Heroku, make sure it's available, press Enter, obtain the cert, and finally ` `heroku certs:add server.crt server.key`.

**Comment by cheeseplus** [comment]
Generating the cert is not and has not been the problem. As we have Heroku configured with Custom Domains that pre-dated SSL support we have to update DNS ALIAS/CNAME to kitchen-ci.herokudns.com. 

Luckily I was able to get control of the registrar yesterday so this is no longer a problem. We're just waiting for the nameservers to update and then SSL should start working.

**Comment by Nowaker** [comment]
Oh, I see, okay.

Cool you managed to take control over the domain! 🎉

**Comment by cheeseplus** [comment]
Now serving HTTPS with redirection of HTTP.
